### PR TITLE
Curl returns not found because filename does not exist

### PR DESCRIPTION
**Pull request by gilacost**

### CODE REVIEW

**Comment by kiriles90** [comment]
This was just renamed, wouldnt you think it was intentional?

**Comment by gilacost** [comment]
Yeah, I was just trying to help 😄. 
In any case, with a dash instead of an underscore will keep on returning a 404 🤷‍♂️ .

Screenshot 2022-03-20 at 14 16 21

https://github.com/popcorn-official/popcorn-desktop/blob/8ac9175fadac795ee98d3716391f038b36fee909/casks/popcorn-time.rb#L7

**Comment by kiriles90** [comment]
@gilacost yes.. @ivan1986 was supposed to rename the previous release server side. (btw all this is to make the builds produced by the actions page and the builds produced when a release is triggered follow the same naming scheme)

**Comment by kiriles90** [comment]
@gilacost yes.. the previous release was supposed to be renamed server side. (btw all this is to make the builds produced by the actions page and the builds produced when a release is triggered follow the same naming scheme)

EDIT: fixed, thanks

**Pull request closed without merging**
