### PR TITLE
Windows 10 native titlebar

### PR DESCRIPTION
**Pull request by geokaralis**
App title bar is now more native and consistent within the windows platform.

Screenshot :
popcorn-native-win10-titlebar

### CODE REVIEW

**Review by Rizwan-Qamar — APPROVED** [review]

**Comment by lucassena** [comment]
Was this not merged because of CI error? Can check?

**Comment by elie-g** [comment]
@lucassena The last commit was on January 11 so I guess the only reason why it hasn't been merged yet is that the maintainer does not maintain the project anymore

**Comment by team-pct** [comment]
Hello @geokaralis  Can you send this PR , Please only send the fix fo native Titlebar

Thank you for your contribution

**Comment by team-pct** [comment]
Can one of the admins verify this patch?

**Comment by pcenta** [comment]
@team-pct 
This can be closed now (merged in https://github.com/popcorn-official/popcorn-desktop/pull/1397)

**Pull request closed without merging**
