### PR TITLE
Add a common torrent health manager to all used pages

### PR DESCRIPTION
**Pull request by ArcticZeroo**
via https://github.com/popcorn-official/popcorn-desktop/issues/1559 , we don't show torrent health on the seedbox page. for some reason the author decided to just leave it as a green icon and never have it update. in addition, every page does it in their own way (well, the same way, but still in two places for no good reason). Instead, I've pulled out the offending code into a `Common.HealthButton` class for use on every page that wants it.

Also ran a reformat on at least one file because the spacing was not consistent with the rest of the project.

### CODE REVIEW

**Comment by kiriles90** [comment]
@ArticZeroo not sure what but something in this PR makes the Seedbox unable to show the torrents currently downloading if you open it from the filterbar.

E.g Open a movie, press download, then exit the Seedbox and try going back to it using the filterbar to see your downloads. It shows up empty. But clearly its downloading, if you press again download on the same movie it says 'cant add duplicate' and also the network traffic suggests something is actually downloading.

I've tried to find what it is but couldnt make head or tails of it from a first look so.. can you take a look at it? Thank you! :)

**Comment by ArcticZeroo** [comment]
Hmm, that's weird. I'll look into it tonight

**Comment by kiriles90** [comment]
Oh, damn that was fast. 
Thank you!

**Comment by ArcticZeroo** [comment]
> Oh, damn that was fast.
> Thank you!

@kiriles90 no problem! fixed in #1603 , there was a race condition with the UI, as well as an issue where we were waiting for the 'ready' event on a torrent that is already ready (and will never emit that event as a result).

**Pull request merged**
