### PR TITLE
Fix issue #439 about errors to display movies covers from amazon domain

### LINKED ISSUE #439: Movie thumbnails don't show up
Operating System Version:
Arch Linux 64 bit

Popcorn Time Version:
Latest linux binary from website

#### Expected Behaviour
Show movie thumbnails

#### Actual Behaviour
At least half of them are missing

#### Steps to reproduce the behaviour
Run popcorntime 3.10 linux 64 bit

### PR DESCRIPTION
**Pull request by Persei08**
fix #439 by using the nwjs 0.18.8 availlable here: https://get.popcorntime.sh/repo/nw/v0.18.8/

### CODE REVIEW

**Comment by VitorVRS** [comment]
I'm not sure if you can update nwjs. Maybe @team-pct give you a light

**Comment by Persei08** [comment]
I'm not sure too, maybe there is some tests to do before using it, we will see :)

**Comment by ChrisAlderson** [comment]
Updating the nwjs version does seem to solve #439, but we need a version of nwjs with video and audio codecs to play the videos. Therefor one does not simply update nwjs. A new version of nwjs is in the works, but it's always a pain to compile it.

@Persei08 thanks for bringing this to our attention, but I'm closing this pull request in favor of a a higher nwjs version with the compiled codecs.

**Comment by Persei08** [comment]
I'm curious how the team is doing the custom nwjs version, Is there some infos somewhere or a script we could learn from? thx

**Pull request closed without merging**
