### PR TITLE
Mouse back button (btn 3) click will close Movie/Tv detail view

### LINKED ISSUE #1327: [Feature request] Back button on mouse
When browsing through the movies we always have to use the **X** in the top right corner to go back to the main page (either movie, serie, anime or favorites). 

Would it be possible to add a back button with the use of our mouse. Most mice have these days more than the left/right and middle mouse button. This would browsing through movies/series a lot easier and quicker.

With my internet browser I can use my mouse button 4 (on the side above my thumb) to go back a page.

### PR DESCRIPTION
**Pull request by Persei08**
Just provide little comfort because the closing icon is too far in
the top right corner. :D

### CODE REVIEW

**Comment by Persei08** [comment]
This do the job but maybe someone have a better solution.
reviews and test welcome :)

**Comment by rafaell-lycan** [comment]
Honestly, you can do the same with the `Esc` button, can't see the advantage of it, but perhaps useful for others. Let's see.

**Comment by kiriles90** [comment]
Not sure if this is the preferred action but you could do a

    backFromDetail: function(e) {
      if (e.button === 3) {
        Mousetrap.trigger('esc');
      }
    },

then the mouse back button does whatever the esc button does everywhere.

**Comment by Persei08** [comment]
@rafaell-lycan it's just a mouse's button shortcut. Not really essential just little comfort.

@kiriles90 thanks, I took your code :P

**Pull request merged**
