### PR TITLE
Update Homebrew Cask

### PR DESCRIPTION
**Pull request by danielbayley**
Addresses #2062, based on these [steps](https://github.com/popcorn-official/popcorn-desktop/wiki/Fix-Crashing-On-MacOS-12#steps) in the wiki.

### CODE REVIEW

**Comment by kiriles90** [comment]
Does this address the codec issues too? Have you managed to build nwjs retaining the previous codec support or its just vanilla nwjs + libffmpeg? If yes then why do this just for homebrew?

(p.s last time I merged a casks PR from you it ended up breaking it for half the people and you nowhere to be found for months until I had to blindly fix it without being a macOS user or having a mac at hand. Just saying..)

**Comment by danielbayley** [comment]
> its just vanilla nwjs + libffmpeg

@kiriles90 Yeah at the moment… like I said based on the [steps](https://github.com/popcorn-official/popcorn-desktop/wiki/Fix-Crashing-On-MacOS-12#steps) in the wiki.

> Does this address the codec issues too? Have you managed to build nwjs retaining the previous codec support

Ideally, it would… But having skimmed over the issue (#2062), am I right in thinking this would have to involve a potentially long time and 60GB of space?

> (p.s last time I merged a casks PR from you it ended up breaking it for half the people and you nowhere to be found for months until I had to blindly fix it without being a macOS user or having a mac at hand. Just saying..)

What was broken, specifically? Well, ideally [the CI](https://github.com/popcorn-official/popcorn-desktop/blob/development/.github/workflows/build.yml#L44-L49) would have tests to catch problems with PRs…

I'm afraid life (/work, and even other open source work) tends to get in the way of open source stuff like this… as I'm forced to prioritize at times. But I mean… the current release, for months, doesn't _even open_ for 100% of the people, only a subset of which would be using Homebrew. Just saying… 😉

**Comment by kiriles90** [comment]
> am I right in thinking this would have to involve a potentially long time and 60GB of space?  

Yes though if successful it would solve a lot of issues, not only macOS specific.

Ok so since this cant be the main nwjs version the app uses due to the missing codecs wont it be a bit confusing for people that Homebrew just uses a different version without any indication its doing so? Is there any way we can keep both and users can choose which to get? (this would also serve as the indication of what's going on, and maybe for the 'why' too if we can add some comments)

**Comment by danielbayley** [comment]
> Yes though if successful it would solve a lot of issues, not only macOS specific.

So can this not currently be done in the GitHub action [`build` step](https://github.com/popcorn-official/popcorn-desktop/blob/development/.github/workflows/build.yml#L5-L6)?

> It was assuming some .db files existed which on new installations didn't

Ah ok, well it's using `Pathname.exist?` method now, so no problem there… I don't have time to actively monitor issues here, but if someone would've just `@` me, that would have been a 5 min fix…

Also, checks could be added to the CI action with `brew style`/`audit`/`install` and/or something like [Brew Test Bot](https://docs.brew.sh/Brew-Test-Bot)…

> Ok, so since this cant be the main nwjs version the app uses due to the missing codecs wont it be a bit confusing for people that Homebrew just uses a different version without any indication its doing so? Is there any way we can keep both and users can choose which to get? (this would also serve as the indication of what's going on, and maybe for the 'why' too if we can add some notes)

I doubt the vast majority of users want to be bothered about codecs, surely they'd prefer it to “just work”…? Maybe something in the README would be good to have (along with maybe a [`caveat`](https://docs.brew.sh/Cask-Cookbook#stanza-caveats)), but I think [passing options](https://docs.brew.sh/Formula-Cookbook#specifying-other-formulae-as-dependencies) to `install` is limited to formulae, not Casks.

**Comment by kiriles90** [comment]
> Ah ok, well it's using Pathname.exist? method now, so no problem there…

I saw, great!

> if someone would've just @ me, that would have been a 5 min fix…

I did, a number of times (I delete my comments later when irrelevant, bit paranoid considering the nature of the app, I will probably delete these ones too one day :)

> I doubt the vast majority of users want to be bothered about codecs,

They might not be bothered with the technical part but they will be bothered if half of the videos in the app don't have sound :stuck_out_tongue: 

> I think [passing options](https://docs.brew.sh/Formula-Cookbook#specifying-other-formulae-as-dependencies) to install is limited to formulae, not Casks.

How about if we had two separate files like it was before but instead of them targeting different branches to target the two nwjs versions? 

> Maybe something in the README would be good to have

I was just about to ask you the same thing, basically if with this PR you could also take a look at the [macOS install](https://github.com/popcorn-official/popcorn-desktop#macos) part of the readme and edit/add/remove anything you see fit.

**Comment by danielbayley** [comment]
> They might not be bothered with the technical part but they will be bothered if half of the videos in the app don't have sound 😛

Exactly my point…

> How about if we had two separate files like it was before but instead of them targeting different branches to target the two nwjs versions?

…So why bother them with 2 separate versions? Surely ideally, the build step would just include the codecs for `macOS-latest`… Is there a reason why it can't?

**Comment by kiriles90** [comment]
By codecs I dont mean just libffmpeg. That's what will result in many of the videos not having audio. None afaik has successfully been able to reproduced the procedure for the custom build we use now and make all of them work (@ivan1986 should know more details about the issues since he tried a bunch of times)

**Comment by ivan1986** [comment]
yes, it now include all codecs, but maybe real make two versions?
with external player codecs not need
just put two versions - 0.44 with codecs, 0.60 without codecs for all systems
it's not hard to build

Also as i say in #2062 not need mae it in homebrew - need only change url of prebuild nwjs to you prebuild
```
  manifestUrl: 'http://popcorn-ru.tk/version.json',
  downloadUrl: 'http://popcorn-ru.tk/nw/',
```

also you may look on this fork - https://github.com/pippyn/popcorn-desktop/commit/1019b90643f965e65ce0b3f2d39cb1991f4f6cf7 - looks he also try to make it, but revert

**Comment by kiriles90** [comment]
@ivan1986 wait a minute because I seem to have lost some episodes. What includes all codecs? You managed to fix the compile script or you're talking about just @danielbayley PR?  

> with external player codecs not need

Yes but many people use it, we cant break it just to update nwjs.

**Comment by ivan1986** [comment]
@kiriles90 no, i fix it partial - it include some codecs, but not all

and because many people use it we need suport 2 versions

**Comment by kiriles90** [comment]
Oh my mistake, I didn't realize you were talking about the nwjs version we currently use. Yeah so my statement above stands.. we cant break the native player! :smile: (50% of the content having no sounds equals breaking it imho)

As for having two versions... its not an optimal solution. Feels very half-backed tbh and I think the average user is already confused enough as to what is going on with versions/builds/apis/everything. We should try to minimize this rather than add to it.

I suggested doing multiple casks files just because macOS has serious issues with the old nwjs versions. For every other OS including the people with macOS where is it working, updating it without completely fixing the codec issue is a downgrade rather than an upgrade, at least in app functionality.

**Comment by ivan1986** [comment]
ok - two casks for mac - i agree

**Comment by Kief5555** [comment]
> yes, it now include all codecs, but maybe real make two versions? with external player codecs not need just put two versions - 0.44 with codecs, 0.60 without codecs for all systems it's not hard to build
> 
> Also as i say in #2062 not need mae it in homebrew - need only change url of prebuild nwjs to you prebuild
> 
> ```
>   manifestUrl: 'http://popcorn-ru.tk/version.json',
>   downloadUrl: 'http://popcorn-ru.tk/nw/',
> ```
> 
> also you may look on this fork - [pippyn@1019b90](https://github.com/pippyn/popcorn-desktop/commit/1019b90643f965e65ce0b3f2d39cb1991f4f6cf7) - looks he also try to make it, but revert

The two links you provided are down.

**Comment by Kief5555** [comment]
@kiriles90 @danielbayley @ivan1986, when you guys get the audio working, (I will try too) please mention me so I can update video and the wiki.

Thanks

**Comment by kiriles90** [comment]
@danielbayley any news with this?

**Comment by danielbayley** [comment]
> when you guys get the audio working

> @danielbayley any news with this?

@kiriles90 I don't have time to mess around with finding the optimum build steps to get the codecs and everything working properly… @ivan1986 @Kief5555 If you guys are working on that, then let me know when you have the working build steps/script (or download link) and I can implement them into this PR…

> As for having two versions... its not an optimal solution. Feels very half-backed tbh and I think the average user is already confused enough as to what is going on with versions/builds/apis/everything. We should try to minimize this rather than add to it.

Agreed. But I would add that having 2 Casks is also not an optimal solution… Surely the best approach would be to have a single Cask that will handle the different build steps, depending on the current macOS version…? Like this kind of thing: https://github.com/popcorn-official/popcorn-desktop/blob/71e1b4ff14b114d71929a3825da169012f1f5f71/casks/popcorn-time.rb#L17

**Comment by kiriles90** [comment]
@danielbayley weird as it sounds I'm pretty sure the old nwjs works for some users with Monterey+.. But I do agree one file is better than two, ..IF its also possible to include the nwjs selection in one file. (as for said selection I'd leave it up to the user if you ask me though I have no strong feelings either way..)

**Comment by danielbayley** [comment]
@kiriles90 How does the [0.4.7](https://github.com/popcorn-official/popcorn-desktop/releases/tag/v0.4.7) release affect this? Does it address any of the issues?

**Comment by kiriles90** [comment]
@danielbayley it doesnt, not changes were made to the cask files (not even the old .tk domain changed). Its all yours though it would be great if you could do it in two files to also keep the old nwjs version as an option.

The only thing it affects is we missed the change to update the bundled readme file with 0.4.7 but we can update it in the repo at least after this PR has been merged.

**Comment by danielbayley** [comment]
> it doesnt, no changes were made to the cask files

@kiriles90 I wasn't referring to those… I meant does the [0.4.7](https://github.com/popcorn-official/popcorn-desktop/releases/tag/v0.4.7) mac build fix/improve any of the issues on macOS (12^)?

**Comment by kiriles90** [comment]
@danielbayley no, afaik those are all nwjs related and will only be resolved with an nwjs update.

**Comment by Kief5555** [comment]
Screen Shot 2022-03-03 at 3 54 51 PM

**Comment by kiriles90** [comment]
@danielbayley are we waiting for something for this? can't it just be made into 2 files (one for the old nwjs one for the new one) and be done with it for now until someone manages to fully compile all the codecs in the new nwjs so we can update everything?

**Review by its0x08 — APPROVED** [review]

**Comment by danielbayley** [comment]
> can't it just be made into 2 files (one for the old nwjs one for the new one)

No need, it will build the latest version of nwjs (`0.64.0`) on 10.12 and higher, or just install the latest build (with the old (`0.44.5`) nwjs on previous macOS versions… but it can also be forced to install the later by setting `export HOMEBREW_POPCORN_TIME_BUILD=false`.

@kiriles90 Should be ready to go for now…

**Comment by kiriles90** [comment]
@danielbayley Great! Merging now. (p.s just clicking the button, I cant test/debug or know what I'm doing with this so its all you atm, you say merge I merge. That being said everything looks good to me code-wise)

**Comment by danielbayley** [comment]
> Btw, if you can take a look at README.md and also update the macOS install instructions wherever you deem necessary it would be awesome.

@kiriles90 See #2497.

**Comment by kiriles90** [comment]
@danielbayley :+1: merging now

**Pull request merged**
