### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by ripper2hl**

### CODE REVIEW

**Comment by VitorVRS** [comment]
Could you explain what you really did?
There are 20 commits here and 1 file.

Did you clean up your repo before?

**Comment by ripper2hl** [comment]
i dont know why have 20 commits xD , i try only update the dependencies, okay clean and up again

**Comment by VitorVRS** [comment]
I saw you changed some major version on dependencies, have you teste them, checked the dependencie api?

Major version usually broke compatibility. As we don't have acceptance test and unity tests, just build getting sucessfull are not enough.

To clean your repo, i suggest delete you fork, fork again and submit a new PR, closing this.

**Comment by ripper2hl** [comment]
Okay no problem, i try write some test and close this, i use my version of popcortime without problems on Fedora

**Comment by VitorVRS** [comment]
My only concern is about major version:

node-tvdb: from 1 to 2
opensubtitles-api: from 2 to 3
torrent-tracker-health: from 0 to 1
xmlbuilder: from 4 to 8 (this can be huge)

I don't know there is a problem, i'm just worried.

Tks for your contribution.

**Pull request closed without merging**
