### PR TITLE
use webtorrent with patches

### PR DESCRIPTION
**Pull request by ivan1986**
Fork content patches

https://github.com/webtorrent/webtorrent/pull/1966 - utp native - need test on windows
https://github.com/webtorrent/webtorrent/pull/1820 - support enc protocol - more connections

### CODE REVIEW

**Comment by kiriles90** [comment]
Ok so I guess merging this for now since it allows us to use the latest WebTorrent version instead of locking to 0.108.6 and also adds utp and enc protocol support.
Of course we should return to the main fork when possible so hopefully the PRs above get reviewed soon. If not or if there are any other issues with this in general we can always rollback and lock to 0.108.6 again until something changes.

**Comment by ivan1986** [comment]
Cool. But I would not hope for a quick merge of requests, at least encryption has been more than a year since the moment of my edits. It probably makes sense to move the fork to popcorn-official/webtorrent

**Comment by kiriles90** [comment]
Unfortunately still broken on Windows, same error as #2051. Reverting for now.

**Comment by ivan1986** [comment]
ok, strage, for me work - testing on win 10

**Comment by kiriles90** [comment]
I didn't try on my win10 installation tbh. I tried on win7 (x64) first that the issue existed last time and it was still there, same error on remote debugging and Popcorn Time wouldn't start both when with old cache+settings from 456 and after resetting everything.

If its something that can be fixed it would be great but if not we cant merge it as it is. Even if it gets confirmed that this only affects win7 we will still break Popcorn Time for like.. 1/5 of the users.

**Comment by ivan1986** [comment]
Just now testing on VW witn win7 x64 - all works, strange

**Comment by kiriles90** [comment]
Hmm, maybe someone at the webtorrent issue would know more what that error is all about.

**Pull request merged**
