### PR TITLE
Add option to disable Anime and Indie tabs

### PR DESCRIPTION
**Pull request by clabby**
This pull request adds the option to disable the 'Anime' and 'Indie' tabs in the advanced 'User Interface' section of the settings.

### CODE REVIEW

**Review by wallydz — COMMENTED** [review]
Why include make_popcorn.sh ?

**Comment by clabby** [comment]
@wallydz Was an accident, must've accidentally included it after changing its file permissions to run it.

**Comment by team-pct** [comment]
Can you Send correct PR without make_popcorn.sh ? Thank you for your Contribution

**Comment by clabby** [comment]
@team-pct Fixed, sorry about that.

**Review by team-pct — APPROVED** [review]

**Pull request merged**
