### PR TITLE
Upgrade nwjs version

### PR DESCRIPTION
**Pull request by kessiler**
It should fix the high cpu usage in OSX.

https://github.com/popcorn-official/popcorn-desktop/issues/70

### CODE REVIEW

**Comment by team-pct** [comment]
We are using a custom nwjs to handle extra codecs

**Comment by kessiler** [comment]
Hm, i see.
Couldn't we update them though?

**Comment by team-pct** [comment]
the guy who used to build nwjs for us left

**Comment by sheepdestroyer** [comment]
jenkins can not automate this?

**Comment by z11h** [comment]
@team-pct any plans to make the nwjs version that popcorn time uses open source here on Github? People might be able to fix it and update it :smile: 

Thanks

**Comment by micopiira** [comment]
NW.js v0.13 stable [was released yesterday](http://nwjs.io/blog/whats-new-in-0.13/). Maybe should upgrade to that one?

**Comment by sheepdestroyer** [comment]
You should maybe rethink the weird-codecs support which prevents you from using upstream NW.js builds.
That would permit you to follow NW.js's releases faster and profits from their bug fixes. 

For those rare vids not using x264, (I call that badly encoded), there is still support of external players like mpv and vlc. It works great and that should be enough. I am sure there is a way to detect codec at playing time and, if not supported, to print a message advising for using Ext Player. Even noobs would not be lost.

**Comment by team-pct** [comment]
@sheepdestroyer we are already aware of that ... but thank you
@micopirra Migrating from 0.12.x to 0.13.x need rewrite , if you are able to migrate Popcorn time code to 0.13.x i will be glad to look into codecs issues 
@ZakariaRidouh https://github.com/nwjs/nw.js/wiki/Building-nw.js , then just edit ffmpeg to compile with new codecs

**Comment by bekicot** [comment]
This pull may also solve the issue related to Mac OS Sierra where the apps closed when hitting the play now button. The console indicate that the error also mention NWJS.

Other people having the same issue
https://www.reddit.com/r/PopCornTime/comments/4uhjc8/help_the_mac_app_is_not_working_now/

**Pull request closed without merging**
