### PR TITLE
file field for season and full serial torrents

### PR DESCRIPTION
**Pull request by ivan1986**
Support file name for select episode in complete season or serial torrent
https://www.reddit.com/r/PopCornTime/comments/ek3vxm/russian_translated_films_and_serials_for/

### CODE REVIEW

**Comment by team-pct** [comment]
Can one of the admins verify this patch?

**Comment by ivan1986** [comment]
https://github.com/popcorn-official/popcorn-api/issues/29

**Comment by VitorVRS** [comment]
Will test

**Comment by VitorVRS** [comment]
@team-pct 
I don't think the official popcorn-api is giving the `file` property aside the `url` property.
I appreciate your effort contributing to the this repository, but this client should be in accord with the api.
I would not merge this PR, not for now.

**Comment by ivan1986** [comment]
ok, when official api will be support serial torrents

**Comment by ivan1986** [comment]
it's actual, but need recreate PR

**Pull request closed without merging**
