### PR TITLE
Fix viewstack

### LINKED ISSUE #725: Keyboard shortcuts
Operating System Version:
      Windows 10 Pro 1709 Build 16299.309

Popcorn Time Version:
      0.3.10 build 277

Download date:
     18/03/2018

#### Expected Behaviour
Esc, Start/Stop, subs sync and volume regulation by keys.
(no command works, these that I have named are those that I consider most important).

#### Actual Behaviour
keyboard commands do not produce effects
Unplug&plug the keyboard doesn't work, neither changing the input method to other language.

#### Steps to reproduce the behaviour
I could not figure out how to reproduce this problem, but it has always been there since I started using popcorn over 1 year ago.

### PR DESCRIPTION
**Pull request by paulfalgout**
Addresses https://github.com/popcorn-official/popcorn-desktop/pull/721#issuecomment-377459811

Definitely a bug in whatever the viewstack is, but I don't think this entirely resolve #725 
When testing the player "p" works fine, but "space" does not for play/pause

I don't think this issue is related to Marionette, but likely Mousetrap because the related code is:
```
            Mousetrap.bind(['space', 'p'], function (e) {
                $('.vjs-play-control').click();
            }, 'keydown');
```

Possibly something is already bound to `space` or something?  I dunno.

### CODE REVIEW

**Comment by Persei08** [comment]
Hi, Thank you for looking at this.

I have reverted your commit to compare before and after, and the mousetrap new code work, so I think we can exclude that.

Your fix seem to fix the issue for movie_detail.js but it seem there is another thing ... maybe with events... I'm not sure, I know nothing about marionette.  
The binding/unbinding functions doesn't seem to be called in the same order than before. 
The unbindKeyboardShortcuts fonctions of movie_detail.js and loading.js are called after the bindKeyboardShortcuts function of player.js and it's why the spacebar and esc keys don't work.

Here my console logs with some debug messages (###) I have added if it can help:
[marionettev2.log](https://github.com/popcorn-official/popcorn-desktop/files/1865726/marionettev2.log)
[marionettev3.log](https://github.com/popcorn-official/popcorn-desktop/files/1865727/marionettev3.log)

**Comment by paulfalgout** [comment]
I'll look into it, but I'm equally lost. this app is about 2% marionette and 98% some awkward event system that is making things hard to trace.  I've never seen a backbone/marionette app that is structured this way

**Comment by paulfalgout** [comment]
I don't have a ton of hope that this will solve everything, but I think it fixes the current issue.

**Comment by Persei08** [comment]
Thanks a lot, It seem to do the job. :wink::+1:

**Pull request merged**
