### PR TITLE
Changed style of the browser list items

### PR DESCRIPTION
**Pull request by 5m1Ly**
I was bored so i decided to make the browser item ui just a little more modern (to my opinion)

### CODE REVIEW

**Comment by 5m1Ly** [comment]
Currently without hover:
afbeelding

Currently with hover:
afbeelding

**Comment by 5m1Ly** [comment]
Currently without hover (series):
afbeelding

Currently with hover (series):
afbeelding

**Comment by kiriles90** [comment]
@5m1Ly nice one! The zoom and overall hover effect looks cool though it might be a bit too different from the old one that some people are accustomed to (also the reason for my personal hesitation for some time experimenting with this). Trying to think how to make it make sense to have both and maybe have an option in the settings for it? (I can help with this). A couple more styles would support the idea of a separate option better though. Thoughts?

**Comment by 5m1Ly** [comment]
Well I get your point and it's not like the current version doesn't do the trick. But great things happen slowly so that why have done a lot more but kept it to a bear minimum here. Also I did the stars separately sinds it already might be to much to my opinion. Next to this I think an "experimental" option of some sorts might be just the thing popcorn time needs to ship features early and get people their thoughts on it before actually implementing them within the application.

**Comment by 5m1Ly** [comment]
Why was it closed @kiriles90?

**Comment by dutchy1001** [comment]
Not sure but it looks to me that it has been added to PCT in the latest dev builds.
Good reason then for closing the topic.

**Comment by 5m1Ly** [comment]
@dutchy1001 so the changes I made are added to the project?

**Comment by dutchy1001** [comment]
I might have been to soon as I cant find the changes back in the code.

**Comment by kiriles90** [comment]
Hi, no I closed it for now because it needs to be optional (a theme, or an option in the settings or something). Many people still like the way the old thumbnails looked and if you check how the app in general looks since.. forever the last thing we do is forcebly change the UI apple-style.. I know personally I had to tiptoe around this many times but tbh I also support this thinking.

Anyway, I'd love for this to be added if like I said can be made optional in some way because we do also have to think about the users who dont like the change.

**Pull request closed without merging**
