### PR TITLE
Update Casks

### PR DESCRIPTION
**Pull request by danielbayley**

### CODE REVIEW

**Comment by Persei08** [comment]
@danielbayley about popcorn-time-beta.rb, isn't it possible to make some changes and remove sha256 check, so it always install the latest stable build available ? Because to me it make more sense the beta script install the latest dev build.

**Comment by Persei08** [comment]
What I wonder is if it is possible to make this script to always download the latest stable dev build while eventually requiring us less work as possible. 
Because for now updating the version values isn't really annoying but the sha256sum... ci only provide md5sum and i think cask no longer accept md5sum. so it will require us extra steps to get the sha256sum... downloading the macos package or using an online service to get the sha256sum. It's those extra steps which annoy me here. :/

**Comment by danielbayley** [comment]
@Persei08 Sure, feel free to change the beta Cask…

**Comment by Persei08** [comment]
i'm on linux, I don't use brew and are not familiar with. 
That's why i was asking you if it's something which can be done without issue (removing the sha256) or what.

I can still dig into cask / homebrew docs, but i'm not able to test on macos :/

edit: Never mind, I found example of what I was talking here: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#examples ;)

**Pull request merged**
