### PR TITLE
add close button to seedbox view

### PR DESCRIPTION
**Pull request by tkSimon**

### CODE REVIEW

**Comment by kiriles90** [comment]
Hmm, if we add one for the Seedbox then shouldn't we add one for the Torrent Collection too?  

Tbh though I dont think we should for either of them since both can also be used as 'Start Screen' and that would be a little weird. The only filter bar buttons/views that have 'close' buttons are Settings and About since with these the filter bar is hidden and there would be no way to exit the view (in the UI anyway, you could exit with `esc`). Also neither of them can be used as a Start Screen.

(*just my thoughts so leaving this PR open for now)

**Comment by tkSimon** [comment]
Maybe it makes sense to explain how I got here. When on the series details view, triggering a download it takes me to the seedbox screen, and I found it quite annoying that there was no easy way to navigate back to the series details view to download another episode. Instead I had to select the series view, find and select my show again, then start another download. 
Once i started looking into the code I noticed that there was in fact a way back, the esc or backspace buttons. Though I think there should definitely be a visual cue to indicates that there's a way back to the previous screen.

I also wasn't aware that one can select seedbox/torrentcollection views as default. Considering this, in combination with the esc/backspace functionality it seems the current behavior is somewhat inconsistent, even without this PR.

For example:
1. Select seedbox as default screen => restart app => seedbox view is shown => press esc => movies view is shown
2. regardless of default screen screen => restart app => select movies/series/anime view => select seedbox from filter bar  => press esc => previous view is shown

It's worth noting that the torrent collection view doesn't behaving like seebox for scenario (1).

I suppose the esc/backspace behaviour is only meant to be use in situations where seedbox is used as a sort of "popup" (as opposed to when users click on the filterbar icon). Maybe it makes sense to show the close button and provide esc/backspace way of going to the previous screen only if seedbox is shown as popup, and not when users select if from the filter bar or have it set as default view. Would be happy to work on this. What do you think.

**Comment by kiriles90** [comment]
But, there is a way to return to the previous view (in your case show_detail). Just press the Seedbox button. Its how the watchlist and torrent collection buttons also work and the favorites one used to before it became a tab on the left some time last year. The only ones of these 'parent' views that have close buttons from these is about and settings since the filterbar is hidden here. Everything else with an 'x' is a child view. The Seedbox isnt a child view its just accessible from show detail. So is torrent collection from movie list or any other view could be made the same but that doesnt change their 'type' (I hope I make sense)

**Comment by tkSimon** [comment]
Hm. I understand that conceptually seedbox isn't a popup. I'm just saying that this hidden esc/backspace support makes it seem like sometime it can be.

Looking for other views that have esc/backspace support just reinforces that:
````
$ grep -rl backspace src/app/lib/views/
src/app/lib/views/seedbox.js
src/app/lib/views/show_detail.js
src/app/lib/views/about.js
src/app/lib/views/settings_container.js
src/app/lib/views/torrent_collection.js
src/app/lib/views/movie_detail.js
src/app/lib/views/file_selector.js
src/app/lib/views/vpn.js
src/app/lib/views/player/player.js
src/app/lib/views/player/loading.js
````

>... sometime it can be.

That's why I though it might not make sense to always show the "x" button, but in those cases where seedbox is shown as a popup. As in, when shown by triggering a download from show_detail or movie_detail, just to indicate that there's a way back.

> But, there is a way to return to the previous view (in your case show_detail). Just press the Seedbox button. Same thing you'd do if you hadnt come from the Download button.

To be honest, that behavior might not be obvious to new users. At least it wasn't to me. Just like I don't expect to get to the previous view when I'm on the movies view and click the movies link again.

Just wanted to point this out. Still, I understand if you don't want to change this. In which case, feel free to close this.

**Comment by kiriles90** [comment]
I can understand the confusion if you hadn't noticed the filterbar buttons are ment to be toggled on/off (the ones on the right, the left ones are tabs, like.. imagine a browser's toolbar). As for the Seedbox.. it doesnt change when accessed via the Download button, it doesnt become something else or some other view's child. It would be false if we gave that impression. But as for a 'popup'.. its basically always a popup, so are the rest of the filterbar buttons. The only ones of those that have close buttons are the ones that are 'full window' (the filterbar is hidden) and you wouldn't be able to exit otherwise. Everything else with an 'x' is some other view's child and not accessible or can be toggled on/off via the filterbar. Aka (and contrary to the Seedbox) it basically doesn't 'exist' until you go and make it exist.

What really puts the nail in the coffin though for me is

> Even forgetting all this, adding a close button will basically result in two buttons ('x' and Seedbox) a few pixels from each other basically doing the exact same thing when clicked. That isnt very good UI design.

**Pull request closed without merging**
