### PR TITLE
Updated README commands as they referred to the old gulp task

### PR DESCRIPTION
**Pull request by edento**
Changes proposed in this pull request:

the readme file contained wrong instructions for building: 'gulp nw:run' task is not found in gulpfile.js. Instead run 'gulp nwjs' for building the app.

### CODE REVIEW

**Review by team-pct — CHANGES_REQUESTED** [review]
You should then add gulp run as 6th step

**Comment by edento** [comment]
'run' opens a broken app for me, rather than just running /build/Popcorn-Time/osx64/Popcorn-Time.app, so I decided to change only the gulp task name.

**Review by team-pct — COMMENTED** [review]
yes but you can do
5. 'gulp nwjs'
6. 'gulp run'

**Comment by edento** [comment]
That is what I meant, it is not working. you have to open the app manually from the build path.

**Review by wallydz — COMMENTED** [review]
What is your OS , try 
npm install
gulp build
gulp run

**Comment by team-pct** [comment]
Actually i am able to build
only by doing `npm install`
`gulp build`
`gulp run`

On the CI `gulp dist`

**Comment by edento** [comment]
I am running OS 10.11, actually the gulp build and gulp run solved the issue. so no need the previous fix at all :) thanks.

**Pull request merged**
