### PR TITLE
Add Custom Movies Server YTS API support

### PR DESCRIPTION
**Pull request by kiriles90**

### CODE REVIEW

**Comment by sativ01** [comment]
Hi @kiriles90 , 
I am playing a bit with the project, wanted to add a "minimum rating" dropdown filter.
I see here that you are reusing the `type` filter in order to have a quality filter on yts movies.
So I am wondering why not adding another filter field?

Thanks!

**Comment by kiriles90** [comment]
Hi, 
I dont think YTS or Popcorn Time's API have such a sorter or some way to do this?
For the type filter, I re-used it because nothing else was using for movies pretty much from the start.

**Comment by sativ01** [comment]
I'll try that.
For popcorn time api, it can be filtered after data is received based on the rating received.

**Comment by test2a** [comment]
Hey. I have been requesting adding filter for parental ratings. Can that be added too

**Comment by kiriles90** [comment]
@sativ01 @test2a there is no such filter in either the api so whatever client based solution would need too many api calls and sorting then discarding of data

**Comment by sativ01** [comment]
@kiriles90 I've managed adding the rating filter but for YTS only, will do a separate github issue and PR to that

**Pull request merged**
