### PR TITLE
Black and Blue theme

### PR DESCRIPTION
**Pull request by BNX070**
edited the Sebastian black & red theme to black & blue, all credits to the original author,

### CODE REVIEW

**Comment by kiriles90** [comment]
@Axe090 can you change all instances of the word 'red' to 'blue' please? It wont break anything and would make more sense to anyone looking at the code.

**Comment by BNX070** [comment]
> 
> 
> @Axe090 can you change all instances of the word 'red' to 'blue' please? It wont break anything and would make more sense to anyone looking at the code.

oh I forgot to do that, Thanks

**Comment by Axe090** [comment]
@kiriles90 On a side note & just to confirm. To edit/make a theme I'll need to find n call the variables defined in the "views" folder to the .styl of whatever theme I go for?

**Comment by kiriles90** [comment]
That is correct. And anything that is not already a variable you will have to make it so, both in the specific views .styl and then in all the current themes and the one you are making. Thats why I said its a bit of a chore doing that (incl testing that nothing broke) and you'd be much better off sticking to the already declared ones.

**Comment by BNX070** [comment]
> That is correct. And anything that is not already a variable you will have to make it so, both in the specific views .styl and then in all the current themes and the one you are making. Thats why I said its a bit of a chore doing that (incl testing that nothing broke) and you'd be much better off sticking to the already declared ones.

Ahan, I think I'll stick with the already defined variables as I don't want to mess anything up & you're right testing would be a hassle. Appreciate the help.

**Comment by Persei08** [comment]
I don't know, there is already the 'Official - Dark' theme which is black(dark grey) & blue... here the differences are it's darker black and brighter blue... 

also IMO the blue is a bit too bright for a dark theme but maybe it's just the habit

Few screenshots to compare:

- Movie list:
PT-Dark_movielist
PT-Seb_DarkBlue_movielist

- Movie detail:
PT-Dark_moviedetails
PT-Seb_DarkBlue_moviedetails

- Show detail:
PT-Dark_showdetails
PT-Seb_DarkBlue_showdetails

**Comment by BNX070** [comment]
> 
> 
> I don't know, there is already the 'Official - Dark' theme which is black(dark grey) & blue... here the differences are it's darker black and brighter blue...
> 
> also IMO the blue is a bit too bright for a dark theme but maybe it's just the habit
> 
> Few screenshots to compare:
> 
>     * Movie list:
>       PT-Dark_movielist
>       PT-Seb_DarkBlue_movielist
> 
>     * Movie detail:
>       PT-Dark_moviedetails
>       PT-Seb_DarkBlue_moviedetails
> 
>     * Show detail:
>       PT-Dark_showdetails
>       PT-Seb_DarkBlue_showdetails

It's just a variant my friend, not such a big deal. Some may like it some won't. Anyhow I'm making/editing some themes, will post once done.

**Comment by Persei08** [comment]
>It's just a variant my friend, not such a big deal. Some may like it some won't.

Yeah, I understand, but at some point all third parties themes were removed for a reason... So, i think we should not add theme just for the purpose of adding theme.

But let's see, after all some themes need to be updated.

Also, can i suggest you this: 
PT-Seb_DarkBlue_showdetails_suggest

line 98:

`    $EpisodeSelectorBg = darken(BlueL,2%)
`

**Comment by BNX070** [comment]
> 
> 
> > It's just a variant my friend, not such a big deal. Some may like it some won't.
> 
> Yeah, I understand, but at some point all third parties themes were removed for a reason... So, i think we should not add theme just for the purpose of adding theme.
> 
> But let's see, after all some themes need to be updated.
> 
> Also, can i suggest you this:
> PT-Seb_DarkBlue_showdetails_suggest
> 
> line 98:
> 
> ` $EpisodeSelectorBg = darken(BlueL,2%)`

Ahan, I'll hold of then on posting any themes. Yes, I was planning to change the selector color. I changed it in the .css but not here. Thanks for informing.

**Pull request closed without merging**
