### PR TITLE
Background Image Updated

### PR DESCRIPTION
**Pull request by thezakman**
Updated background to match the new 'about view

### CODE REVIEW

**Comment by thezakman** [comment]
image

**Comment by kiriles90** [comment]
May I ask what's changed? Other than a reduction in filesize and the new image being slightly more blurry I cant see any other difference.

**Comment by kiriles90** [comment]
Btw, I see from your screenshot that you are using the older 0.4.4 release version. Update to the latest dev build from ci.popcorntime.app (439 at the moment) which is pretty much in line with the `development` branch. (and also includes your commit)

**Comment by thezakman** [comment]
Now i get it, the release builds are beeing pulled from the  development branch.
Sorry for this, I saw that my commit from 2 years ago was accepted, but never saw it on the app. 

My bad!

**Pull request closed without merging**
