### PR TITLE
Remove unused `en` translate

### PR DESCRIPTION
**Pull request by IgorPolyakov**
Hello! I wanted to make better Russian translate, but noticed that source (en) has many unused words.
I write small script for checking it

```ruby
require 'json'

def load_translate(lang: 'en')
  file = File.read("src/app/language/#{lang}.json")
  JSON.parse(file)
end
en = load_translate(lang: 'en')

en_keys_remove = []
en.keys.each do |key|
  grep_out = `grep -r --exclude=\"*.json\" \"#{key}\" . `
  if grep_out.size.zero?
    en_keys_remove << key
  end
end

en_keys_remove.each do |en_key|
  puts "remove key: #{en_key}"
  en.delete(en_key)
end

File.write('src/app/language/en.json', en.to_json)
```

Result is in PR.

I hope it will be useful)

### CODE REVIEW

**Comment by team-pct** [comment]
Can one of the admins verify this patch?

**Comment by team-pct** [comment]
Sent the en.json to transifex

**Comment by IgorPolyakov** [comment]
Sorry, I have a question)

[CONTRIBUTING](https://github.com/popcorn-official/popcorn-desktop/blob/development/CONTRIBUTING.md#contributing-to-popcorn-time) guide has link to [transifex/butterproject](https://www.transifex.com/butterproject/public/), but also I found [transifex/popcorn-time](https://www.transifex.com/popcorn-time/popcorn-time-app/dashboard),

what link is the correct?

**Comment by team-pct** [comment]
transifex/popcorn-time

**Pull request merged**
