### PR TITLE
filters by tabs - thanks El-Virus

### PR DESCRIPTION
**Pull request by ivan1986**
https://github.com/popcorn-official/popcorn-desktop/compare/development...El-Virus:popcorn-desktop:dyn-types

### CODE REVIEW

**Comment by El-Virus** [comment]
But, wasn't [my PR](https://github.com/popcorn-official/popcorn-desktop/pull/2773) rejected?

**Comment by ivan1986** [comment]
@El-Virus looks like not like this mr too

**Comment by El-Virus** [comment]
Yeah, kiriles did have a point though. I mean, that could technically be fixed with yet another checkmark.

What do you think, do you want me to implement that? Or do you think that would be just bloating the settings page?

**Comment by El-Virus** [comment]
I do agree with you, that's why I didn't say anything else, my initial thought was that it's kind of pointless having the option on the menu when you don't watch a type of content.

Uh, wait a minute... A better way of doing this is to disable it if you have no items of a certain type on your bookmarks (even better, the bookmarks db keeps track of the type of the item). That would be better in all cases, even when you haven't disabled a tab (given that it's quite pointless to filter by a certain type if you haven't bookmarked any items of that type).

**Comment by El-Virus** [comment]
I'll have a crack at it tomorrow, see if I can make it work. That way we'll have a cleaner UI.

**Pull request merged**
