### PR TITLE
Fix for TVST issue #113

### PR DESCRIPTION
**Pull request by VitorVRS**
The first commit is due to syncing my fork with upstream.
The second commit is my fix for the issue (#113).

### CODE REVIEW

**Comment by team-pct** [comment]
Can you fix the conflict so that i can Accept your PR ?

**Comment by VitorVRS** [comment]
I'll try to revert the "???" commit. I've had some issues on syncing from upstream with submodules :(

**Comment by team-pct** [comment]
Try to clean your Repo or wipe it and create a new one

**Comment by VitorVRS** [comment]
Added new commit with fixes.

**Comment by VitorVRS** [comment]
That's it, sorry for the many commits :disappointed:

**Comment by VitorVRS** [comment]
Closing, i'll make an new PR.

**Pull request closed without merging**
