### PR TITLE
Background Image Updated

### PR DESCRIPTION
**Pull request by thezakman**
Updated background to match the new 'about view

### CODE REVIEW

**Comment by thezakman** [comment]
image

**Comment by Persei08** [comment]
Development is done on development branch.  
Master branch is sync with development branch when there is a new release.

**Comment by thezakman** [comment]
> Development is done on development branch.
> Master branch is sync with development branch when there is a new release.

Sorry I didn't understand. What is wrong here?
I pulled to the master branch, not development branch.

**Comment by reddo** [comment]
I think he meant for you to open the pr against the development branch

**Comment by thezakman** [comment]
> I think he meant for you to open the pr against the development branch

Thanks I understand now, I thought it was not to pull for development branch, but for the master,

**Comment by Persei08** [comment]
@thezakman we don't accept PR to master branch directly. PR have to be done on development branch.

When a new pocorntime release is released the master branch is updated with all change from development branch... it's how the master branch here.

And on the development branch you already updated this file 2 years ago... so i don't know if you want to overwrite it with this image which have a lower weight or what. But if you want you need to create a PR for development branch

**Pull request closed without merging**
