### PR TITLE
Update gulpfile.js

### LINKED ISSUE #1719: yarn dist not working on windows
i get the following error when building either win32 or 64:

[01:20:43] 'prepareUpdater:win' errored after 12 ms
[01:20:43] Error: File not found with singular glob: C:\Users\...\popcorn-desktop\build\Popcorn-Tim
e-0.4.4-win64-Setup.exe (if this was purposeful, use `allowEmpty` option)

i can test changing the gulpfile if needed

### PR DESCRIPTION
**Pull request by riclas**
fixes #1719

### CODE REVIEW

**Comment by kiriles90** [comment]
Nice!

@vageliskatsiotis could you test this by any chance?

**Comment by vageliskatsiotis** [comment]
@kiriles90 hi.

As a matter of fact, I've made the build today on Windows. Worked like charm. You can merge the pr.

@riclas thanx man

**Comment by riclas** [comment]
even though it now builds, after installing popcorn doesn't work... the only way i was able to run it was from git doing yarn start.

**Comment by vageliskatsiotis** [comment]
> even though it now builds, after installing popcorn doesn't work... the only way i was able to run it was from git doing yarn start.

Confirm that, but you do not need to yarn start each time, just get a shortcut to the exe file. If creating an installer is the question here, I believe it fails, yes.

**Comment by riclas** [comment]
No, i was able to create the installer, and use it to install. but running the installed instance, or the exe on the build folder fails to run popcorn. i'm only able to run the dev version through yarn start

**Comment by Persei08** [comment]
So, I close this one. #1704 / #1719 are related to dev environment setup, see comments in #1704

**Pull request closed without merging**
