### PR TITLE
use file name in selector

### PR DESCRIPTION
**Pull request by ivan1986**
use in file selector file name, not index

### CODE REVIEW

**Comment by kiriles90** [comment]
@ivan1986 any chance you can check the 'Download' and 'Play next episode automatically' functions? They still play the wrong (and always same) episode when its a full season torrent.

**Comment by ivan1986** [comment]
yes, i checking it now, but find this refactoring
for downoad need some rewrite adding logic

**Comment by kiriles90** [comment]
Yeah I was afraid of that.. well, the simpler it can be done and the more stuff it can share with the 'Watch now' function the better I guess.

**Comment by ivan1986** [comment]
fixed and some refactorion of streamer.js

**Pull request merged**
