### PR TITLE
Localize

### PR DESCRIPTION
**Pull request by ivan1986**
YTS is now multilang provider
I think need support localization

titles and posters - with interface
content - custom select of content language or default same as interface

but i think need do something with update issue before merge it

### CODE REVIEW

**Comment by kiriles90** [comment]
@ivan1986 looks good but I think the 'Content language' option should be moved up with the rest of 'Localization' and set to 'All' by default (not 'English' or 'Same as UI language', we don't want to hide content in different languages by default).

Also I think it needs a restart to work correctly(?), something weird is going on without one when switching/refreshing tabs so I guess we should trigger the 'Please restart' notification in the settings or fix whatever causes the weirdness if possible. If it can be fixed to not require a restart it would be very nice if it can also be made into a filter-bar filter/dropdown for quick access. (ofc while still keeping the one in the settings for defaults)

**Comment by ivan1986** [comment]
We can not set 'All' - in shows we not have language level and in movies we lost this level in provider - `src/app/butter-provider/movie.js:40`
need change internal structures for show all languages in same time

**Comment by kiriles90** [comment]
Wait so.. if I got this right.. the official API just has 'en' for everything so shows eveything. YTS uses yts provider and that one works, but.. was your API always not able to get the torrents for non-english movies or you changed recently? Because I can see non-english movies with it and build 454 but no torrents available when clicked.

**Comment by ivan1986** [comment]
YTS was only english when old official api was writen, and now if it's not stopped we will be see mix in all languages
If we try show all languages in same time we have not language key
in my api i fix yts parser and of couse you not see non-english movies

now structure is 
`model.torrents[quality] = torrent`
for select language in plase we need
`model.torrents[lang][quality] = torrent`

we need change pointer to current lang subarray as same as when we select quality, but we not have this code in movie-detail and show-detail (in show we also haven't select lang)

**Comment by ivan1986** [comment]
Looks like we can suport `all`, but i think it's not good idea set it by default.
Need add support to server and add change language handler, but i think not in this feature

**Comment by ivan1986** [comment]
looks like all work
on old server, on ru-tk, on yts.mx
of couse localization only on ru-tk

**Comment by ivan1986** [comment]
this merge not break, but also not give anything on old servers
localization will be fork fine only on ru-tk server

The question
what better order of actions

- release 0.4.5 - many changes, we have working servers on sujest now, not need to test
- merge this PR - no effect for users, who use original server and yts
- update main server - change dns, or change config - without this only users of ru-tk server can see localized content

**Comment by ivan1986** [comment]
All ready to merge

**Pull request merged**
