### PR TITLE
Re-add peers when resuming a paused torrent

### LINKED ISSUE #1988: cannot resume stopped episode
I'm on Windows 10 and have the latest version dowloaded from Jenkins. 

I play an episode with about a dozen of seeds (and more peers), I press ESC and get out of it. I play it again, it would play what was already downloaded but stays stuck at 0 peers and 0 seeds. I've read some closed issues but:

- I think after waiting 5 minutes is reasonable to assume nothing will ever happen
- I deleted all the items in "seedbox", now stuck at "connecting"
- unchecking the "seedbox" feature in the settings only hid the button, no change in behaviour
- I deleted the cached files, no change
- there's a setting "activate udate seeding" which doesn't change anything either
- streaming or locally watching doesn't make a difference

Unbenannt

So basically my only chance to watch an episode is to not ever interrupt it. Other episodes will work, unless I interrupt them - then they go dead, never ever managing to (re)connect. Is there some torrent intrinsic feature which kicks me out in some way?

### PR DESCRIPTION
**Pull request by tkSimon**
Only relevant when seedbox is enabled. Fixes #1988

### CODE REVIEW

**Comment by tkSimon** [comment]
tested and squashed

**Comment by kiriles90** [comment]
Is it just me or there's some issue with the download speed after resuming? (not saying its caused by this PR its probably a pre-existing issue and possibly has to do with WebTorrent itself)

Either way merging this. It solves the removed peers issue. :+1:

**Comment by tkSimon** [comment]
>Is it just me or there's some issue with the download speed after resuming?

Was that related to 5e3f64b91565ad9981083ef480aff6693300229a?

**Comment by kiriles90** [comment]
No that was just to fix the active torrents limit.

**Pull request merged**
