### PR TITLE
Fix for Favorites filter for "TV"

### PR DESCRIPTION
**Pull request by Devologger**
#1598 a follow up fix in attempt to fix favorites TV filter.

### CODE REVIEW

**Comment by kiriles90** [comment]
Not 100% sure how it all ties together at the moment but there are more 'tvshow' instances in the code.

`/src/app/lib/models/show_collection.js` ([10](https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/lib/models/show_collection.js#L10))
`/src/app/lib/providers/favorites.js` ([125](https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/lib/providers/favorites.js#L125), [146](https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/lib/providers/favorites.js#L146))
`/src/app/lib/providers/watchlist.js` ([235](https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/lib/providers/watchlist.js#L235))
`/src/app/lib/views/settings_container.js` ([142](https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/lib/views/settings_container.js#L142), [145](https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/lib/views/settings_container.js#L145), [151](https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/lib/views/settings_container.js#L151), [198](https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/lib/views/settings_container.js#L198), [388](https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/lib/views/settings_container.js#L388), [389](https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/lib/views/settings_container.js#L389))

Could someone take a look at this?

**Comment by Persei08** [comment]
What does it fix exactly, because favorites filter seemed to works well in #1598 for me ?

**Comment by Devologger** [comment]
@Persei08 Did you try setting Favorite Filter to "TV"? Try favorite a tv series and then test it. For me it didn't work on latest build. Renaming that did the job for me, anyone else can confirm this? Might be only me.

**Comment by kiriles90** [comment]
@Devologger Hmm #1598 worked for me too. Thats why I linked all the other instances above because I wasnt sure what this is ment to fix either.

**Comment by Persei08** [comment]
@Devologger Yes I have tested it, it was working both with existing favourites and also after I reinit PT.

But here I don't understand how everything work together, I've looked at it some months ago but haven't took the time to well understand and now I barely remember things :/

I'm not sure what to do for now, i will appreciate more feedback/explanations.

**Comment by Devologger** [comment]
Yes, #1598 is indeed working as expected. I just did a clean build and flushed the db for it to work. Should I close this pull request then?

**Pull request closed without merging**
