### PR TITLE
file field for season and full serial torrents

### PR DESCRIPTION
**Pull request by ivan1986**
https://www.reddit.com/r/PopCornTimeApp/comments/knzims/can_find_the_show_friends/

Support file for client
It's a big issue for old serials
Also eztv has season torrents

### CODE REVIEW

**Comment by kiriles90** [comment]
Anyway we can fix the filesize? It registers as 0 so Popcorn Time automatically jumps to 'Done' mode even if some parts (e.g the download) continue.

**Comment by ivan1986** [comment]
Yes, it tested more that year - from start my server.

sometime parser can not get file size from page - i add 1gb default

**Comment by kiriles90** [comment]
Hmm, then they will show up as never completing download, ones smaller than 1gb, but anyway, since this only affect serial torrents on RU, and before this they were just broken and all episodes playing same one, I guess merge and if we find a better solution for filesize later we can merge that too. Tell me whenever you are done to merge it.

**Comment by ivan1986** [comment]
As i see, only the statistics in the pop-up window is violated, and the episodes themselves download and watth normal, so this seems to be a very minor problem.

The best solution that I see is to write a small microservice torrent client that will convert magnet links into torrent files - then it will be possible to extract completely correct information about the size of the files and their names from them, which will be just great for all serials, because you don't have to get a list of files from the page and some trackers will not need a user.

**Comment by kiriles90** [comment]
Ok merging.

**Comment by kiriles90** [comment]
@ivan1986 rechecking this now, and e.g for your example 'Friends' it plays the same episode whatever I click. E.g for season 8 its all s08e01, and for s09 all s09e23e24. Any idea what's going on?

**Comment by ivan1986** [comment]
Hm, strange - it's first time i see
https://github.com/popcorn-official/popcorn-desktop/pull/1960
torrent has plus one folder

Season 1/Friends (1994) - S01E06 - The One With The Butt (1080p BluRay x265 Silence).mkv

Friends (1994) Season 1-10 S01-S10 (1080p BluRay x265 HEVC 10bit AAC 5.1 Silence)/Season 1/Friends (1994) - S01E06 - The One With The Butt (1080p BluRay x265 Silence).mkv

ok, working, but i will write torrent extractor on server

**Pull request merged**
