### PR TITLE
Fix Homebrew Cask

### PR DESCRIPTION
**Pull request by danielbayley**

### CODE REVIEW

**Comment by kiriles90** [comment]
Nice. Can someone verify this please?

**Comment by kiriles90** [comment]
@danielbayley Can you resolve the conflicts please so this can be merged?

**Review by nxame — APPROVED** [review]

**Review by nxame — CHANGES_REQUESTED** [review]
@danielbayley Can I get access to you repo to fix this conflicts?

**Comment by danielbayley** [comment]
@kiriles90 @shekhardesigner Should be fixed now…?

**Comment by danielbayley** [comment]
@kiriles90 @shekhardesigner Why are there 2 separate downloads for this (`Popcorn-Time-0.4.5+43.g4fc2f4e4_osx64.zip` and `Popcorn-Time-0.4.5-Mac.zip`)? This releases process is a mess to work with!

**Comment by kiriles90** [comment]
@danielbayley One in the 0.4.5 release version from June 20 and the other one is a newer build from July 10 (g4fc2f4e4 is the HEAD)

**Comment by ivan1986** [comment]
@kiriles90 we still need edit sha256 in cask if we want add commits bulds, i think not need add this builds to repo

**Comment by kiriles90** [comment]
I know but.. at least easily confused users wont have to deal with it. Now they see 0.4.5 and 0.4.5+43.g4fc2f4e4 and justifiably go.. "These are different, what is the difference/which one is best/which one do I download?". Maybe just leave 0.4.5 for now and hopefully localization and dht etc are done quickly so we can release 0.4.6. Also if you want to keep an archive of older builds maybe put in folders if easy? Though personally I dont see the benefit of someone downloading a broken 0.4.4 or even 0.4.5 if 0.4.6 is out and running better, there is an archive here in the repo if they want older versions.

**Comment by shekhardesigner** [comment]
For this PR's purpose sake, I suggest we merged this so that the Homebrew installation is fixed. @kiriles90 

Thank you @danielbayley for quick turnaround.

**Comment by kiriles90** [comment]
@shekhardesigner Ok merging and we can edit later.

**Pull request merged**
