### PR TITLE
WebTorrent Implementation

### PR DESCRIPTION
**Pull request by team-pct**
credits @VitorVRS 
Changes proposed in this pull request:
- Switch from Peerflix to Webtorrent
- New updater using Torrent instead of HTTP Servers

I've read the [Contributor License Agreement](/CONTRIBUTING.md#contributor-license-agreement)

### CODE REVIEW

**Comment by ChrisAlderson** [comment]
@VitorVRS I'm pretty sure this download time is incorrect. I have this issue on the `feature/webtorrent` branch, but not the `development` branch.

downloadtime

**Comment by ChrisAlderson** [comment]
@VitorVRS nevermind, I solved the issue. `torrent.timeRemaining` returns a value in milliseconds while the `remainingTime` function expects a value in seconds.

**Comment by DiegoRBaquero** [comment]
Just wondering: why use old version of WebTorrent?

**Comment by VitorVRS** [comment]
This was made on mar/april :) just now was accepted ;)

**Comment by DiegoRBaquero** [comment]
@VitorVRS Use 0.x as version 0.x.y works as if x was a major version (for versions < 1.0.0)

Once WebTorrent 1.0.0 is published you can go back to use the caret.

**Comment by VitorVRS** [comment]
Yeah we know, we just missed that, thanks for noticing.

**Pull request merged**
