### PR TITLE
Theming

### PR DESCRIPTION
**Pull request by pcenta**
Since there are native dark modes in basically every supported OS and that's what almost everyone uses, I think there's no need to have implementation of custom title bar. At the same time, we get some simplification and we get rid of some minor bugs.
Tested only on Windows:

image

### CODE REVIEW

**Comment by kiriles90** [comment]
What happens if someone uses an older OS (e.g Windows 7 or 8) or doesnt have dark mode on?

**Comment by pcenta** [comment]
> But what happens if someone uses an older OS (e.g Windows 7 or 8), or doesnt have dark mode on, or has some other weirdness going on with his default titlebar?

Weirdness like what?
Regarding other operating systems, user will get default OS title bar. It looses that connection that in Win 7 user sees dark title bar but with Win 10 styling.

**Comment by kiriles90** [comment]
But wouldnt that suck a bit for everyone not using Windows 10? Most OS default title bars dont match at all with Popcorn Time's UI style.

**Comment by pcenta** [comment]
From the point of matching style yes, but since PT uses Win 10 style, now they see match in colour but mismatch in style.
I guess it would be best if there were screenshots of app on different systems.

**Comment by kiriles90** [comment]
How would someone with Windows 7 or some Linux build that has a glass titlebar will see match in color? (sorry if I'm annoying with all the questions, just trying to understand and think ahead)

**Comment by pcenta** [comment]
I get you and support constructivedebate. I meant matching in style (aero glass title bar in all Win 7 windows instead of one that matches Win 10). But colour wise it would be a mismatch. 
But one thing that I discovered is that with current approach we put one colour in title bar regardless of state (focused/unfocused). That behaviour is opposite of what Windows does (probably true for all other systems) and changing title bar depending if windows is in focus.

**Comment by kiriles90** [comment]
I agree with you having an 'unfocused' color would be great. But this will take the matching style out of everyone else not using Windows 10 with dark mode on. It will be like the Popcorn Time window is handing off whatever titlebar style they happen to have instead of all being one piece.

**Comment by pcenta** [comment]
I like the idea of having native titlebar.
But at the same time, is there a point in puting effort in development for old OS eg. Win 7 that is officially unsupported from beginning of the year. I do understand that people still use it, but it's the question of supporting it in cosmetic sense.

**Comment by kiriles90** [comment]
Is it just Windows 7? Or is it everyone else not using Windows 10 and dark mode on? And for what? So Windows 10 users can get an unfocused shade? (in what also, everything else in Popcorn Time is skinned, even the checkboxes to have a common UI style)

**Comment by pcenta** [comment]
Probably this means mostly Windows 7 users. Ubuntu or majority of Linux systems use darker colour scheme by default (Mac OS being an exception here).

**Comment by kiriles90** [comment]
Even Windows 10 without dark mode on will have a bright blue titlebar on a completly dark window.. And thats even assuming you are using the default dark Popcorn Time theme, if not it perplexes things even more. The only one this commit suits is people with dark mode and win 10..

**Comment by pcenta** [comment]
Yes, I get the point. I'm closing this PR and I'll try to look into adding option to adding a setting for native title bar.

**Comment by kiriles90** [comment]
Thank you! I'll have a look too and will let you know if I find anything if you havent made a new PR by then.

**Pull request closed without merging**
