### PR TITLE
Front-End

### PR DESCRIPTION
**Pull request by leutrimdemiri**
Hi!

This is magneta theme that i'm working my request is can it be official theme on popcorn time? that would be awesome. I'm still working adding some new features.

29tz4to4v9y51
ebkmoto4v9y51
g45x5zo4v9y51
pc4sfvo4v9y51

### CODE REVIEW

**Comment by Persei08** [comment]
Hi, you compared the wrong branch from wrong project. 

I'm not sure which files you have really modified here, but what you should submit is just a .styl file going into `src/app/styl/` 

Your theme must be based on the "development" branch of popcorn-desktop project. Because there are lot of unwanted commits and modified files in your PR here. 

Else based on the screenshots, IMO, I think the magenta titlebar is too catchy, It's jump to my eyes in first but it isn't really useful. What should jump to my eyes first, should be the action buttons ("watch now", etc..) and the covers. And the highlighting color in player should be magenta too but I guess your showing us your work in progress.

Maybe someone with better UX knowledges will give you better advices.

**Comment by kiriles90** [comment]
Like @Persei08 said you forked and edited a wrong branch. No harm done though just fork this repo not butter, and edit on the development branch. Then just duplicate one of the ready themes in `src/app/styl/`, rename it and edit anything you want in it. I can help if you need some help with converting your css to styl but finish the css first then if you need help just tell us.

**Comment by leutrimdemiri** [comment]
> Like @Persei08 said you are trying to merge a wrong branch. No harm done though just fork this repo not butter, and edit on the development branch. Then just duplicate one of the ready themes in `src/app/styl/`, rename it and edit anything you want in it. I can help if you need some help with converting your css to styl but do finish the css first then if you need anything regarding the conversion just tell us.
> 
> Personally I do like the theme (and the pink too, matches @Persei08's identicon color :D) I'm just not sure how much of it we will be able to get into the styl file without too much trouble because it looks like you're editing some pretty custom stuff. Finish it though and we will see about this.

i mean on the first pic i used vibrance (edited on photoshop) not sure why i did that, now i understand it looks more catchy color, but as a ui designer i love the color matching, the buttons and everything,  i didn't want to look everything on magneta so i used some blue, but i'm still finding a way to look more cleaner. also i edited some other files like movie-detail.tpl because of buttons and the description movie like " YEAR: 2020  TIME: 124min. and also i edited the player too i used pure svg icons.

**Comment by leutrimdemiri** [comment]
> Hi, you compared the wrong branch from wrong project.
> 
> I'm not sure which files you have really modified here, but what you should submit is just a .styl file going into `src/app/styl/`
> 
> Your theme must be based on the "development" branch of popcorn-desktop project. Because there are lot of unwanted commits and modified files in your PR here.
> 
> Else based on the screenshots, IMO, I think the magenta titlebar is too catchy, It's jump to my eyes in first but it isn't really useful. What should jump to my eyes first, should be the action buttons ("watch now", etc..) and the covers. And the highlighting color in player should be magenta too but I guess your showing us your work in progress.
> 
> Maybe someone with better UX knowledges will give you better advices.

as i said to @kiriles90 one picture is edited and it uses vibrance that's why titlebar is too catchy, but the other thing is that i'm a bit ui designer and i know how this works, i know what colors to use. i mean you should be thankful for what i did because people will love if they see that not that i care but i just want to get involve and help, sorry if im wrong. and yes i did modified the css file of sebastian black i think that's what is called.

**Comment by Persei08** [comment]
>i mean you should be thankful for what i did because people will love if they see that not that i care but i just want to get involve and help, sorry if im wrong. and yes i did modified the css file of sebastian black i think that's what is called.

@leutrimdemiri Sorry don't be wrong, I am thankful you have interest into popcorn-time, want to contribute and make a theme. 
I don't wanted to give you a bad feeling or sound rude. I'm not against the colours... dark blue and magenta/pink match well, it's not a problem... I just find the titlebar too catchy and I think the light blue buttons and player elements will look better in magenta... that's what I had in mind... and you also said it wasn't finish. I don't wanted to offense you, but I understand a bit, I asked myself if I wasn't too concise/direct.

For your pull request there are [180 commits](https://github.com/popcorn-official/popcorn-desktop/pull/1815/commits), [editing 81 files](https://github.com/popcorn-official/popcorn-desktop/pull/1815/files) from april 2016 to november 2016... we will not merge those it will break the app. What we need is just your own commits of your theme file.

If your not too familiar with git or what, maybe it's better you [open a feature request](https://github.com/popcorn-official/popcorn-desktop/issues/new?assignees=&labels=&template=feature_request.md&title=) for your theme and we could discuss there to help you or find a way for you to submit your theme.

**Comment by leutrimdemiri** [comment]
> If your not too familiar with git or what, maybe it's better you [open a feature request](https://github.com/popcorn-official/popcorn-desktop/issues/new?assignees=&labels=&template=feature_request.md&title=) for your theme and we could discuss there to help you or find a way for you to submit your theme.

again sorry for pull request my bad, i'm new to github. it would be my pleasure if we talk in chat or somewhere with you.

**Pull request closed without merging**
