### PR TITLE
Show all torrents (movies, shows, and tracker icons)

### LINKED ISSUE #2505: Source name of movie on main film page
**Is your feature request related to a problem? Please describe.**

Each film or series have a file name that will be streamed/downloaded to your device. 
Reveal of the source name to determent the "base" quality of the film.
No matter of the 480P to 2160P picture, quality is often upgraded to a higher "P" then the film is, special when the film is cropped to hide some subtitles or an upgraded cam version (like the bad example posted below)

**Describe the idea you'd like**

An extra line to inform what the file name is.
Good Example:
Fantastic Beasts The Secrets Of Dumbledore 2022 HDR 2160p WEB H265-NAISU
Bad Example:
Fantastic Beasts The Secrets Of Dumbledore 2022 720p Cam X264 AC3 Will1869
(how can a cam version be 720P imho)
I understand that file names not always say what it is, but you have some extra info to decide to watch it or not.

I know this can be seen already when using the download option or when you start to stream this, but it would be nice to know before you start the film (there is nothing worse then to look forward to a film and then finding out the quality is crap).

### PR DESCRIPTION
**Pull request by ivan1986**
Show all torrents for movies and shows
Not only one for quality with max seeder count

Icons for torrent list
Download from server by provider name

### CODE REVIEW

**Comment by milouk** [comment]
Hey Ivan, 

First of all this is a killer feature. A feature that has been missing from PT while other Platforms e.g Stremio (Torrentio) have. 

I tested it and some comments i have are the following:

1) Although if i click "More" I see 1080 quality streams, the 1080 indicator is greyed out. (see photo)
Screenshot 2022-03-10 at 20 14 25

2) While in Series it is not clear to me what the left list is for. (see photo)
Screenshot 2022-03-10 at 20 15 36

3) It would be nice to have a filter for the stream order e.g (seeders / quality / provider)

4) I can't see any rarbg  / piratebay torrent. Also it would be nice adding more providers e.g Torrent 9 etc.

Thanks again for this feature. It was 100% what was missing from PT

**Review by its0x08 — APPROVED** [review]

**Comment by Lcchy** [comment]
Great feature!

I tried it out but I'm getting "Error loading data, try again later..." when trying to open a series via the favorite tab, and for a movie it opens but without any of the bottom buttons that allow streaming or downloading.
It works great when accessing the content via the other tabs.

Lastly, it seems that for a series, the torrent list does not update depending on the selected episode and is showing very general results, from various seasons.

Let me know if I can help in any way, I am not at all familiar with the codebase but I'd be happy to test/report logs.

**Comment by ivan1986** [comment]
> open a series via the favorite tab

ok, thanks for testing, try to retest it and fix

> Lastly, it seems that for a series, the torrent list does not update depending on the selected episode and is showing very general results, from various seasons.

For serials it have two lists of torrents - for serial and for selected episode, for selected episode change, but for serial list load once time

**Comment by Lcchy** [comment]
Thanks for getting back! 

> For serials it have two lists of torrents

Ah I see it on the screenshot posted by @milouk, on my install it only shows the torrent list for the whole series, not the one for the episode on the right.

EDIT: Now I see it, it only shows for certain series. For example, it is there for the series "The Simpsons" but not for "Peaky Blinders". Maybe the search request times out for certain series?

**Comment by Lcchy** [comment]
I am getting these kinds of error messages (although I am not sure they are all linked to the issue I described in my last message):

```
[73536:73536:0402/212318.765999:ERROR:gl_surface_presentation_helper.cc(259)] GetVSyncParametersIfAvailable() failed for 10 times!
[73536:73536:0402/212319.802465:ERROR:gl_surface_presentation_helper.cc(259)] GetVSyncParametersIfAvailable() failed for 11 times!

(node:73555) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 data listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:73555) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:73555) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit

[73555:74232:0402/213653.949426:ERROR:stun_port.cc(96)] Binding request timed out from 192.168.1.x:53943 (wlp0s20f3)
[73555:74232:0402/213653.950069:ERROR:stun_port.cc(96)] Binding request timed out from [2a01:4b00:8493:x:x:x:x:x]:33699 (wlp0s20f3)

**Comment by ivan1986** [comment]
no, some broken in select providers
it's old code 2018 year
something break favorites

**Comment by ivan1986** [comment]
ok, fixed, but need refactoring :rofl:

**Comment by ivan1986** [comment]
Seasons and Episodes torrents depends on current serial and tracker
episode give only eztv, and other trackers give torrents with many series

**Comment by Lcchy** [comment]
Nice! The favorites work now.

> Seasons and Episodes torrents depends on current serial and tracker

I understand, then this is more a problem with how popcorn time handles the torrent search in general.
It would so nice to be able to customize the torrent search engine, maybe even searching through Jackett!
Can you point me to the code where the search is done and where the different sites/trackers are used if you know? Thanks

With this fix I don't have any problems that are directly linked to your PR, so it looks good to me, for what its worth :)

**Comment by ivan1986** [comment]
Yep - https://github.com/popcorn-time-ru/popcorn-ru/tree/master/src/Spider
Jackett as i know can not parse all tracker - it interface for search, need spider, but if write mapper for it - it may be usefull
If you want you may help to add more trackers, just need write class for tracker and parser will be work

**Comment by milouk** [comment]
> Yep - https://github.com/popcorn-time-ru/popcorn-ru/tree/master/src/Spider Jackett as i know can not parse all tracker - it interface for search, need spider, but if write mapper for it - it may be usefull If you want you may help to add more trackers, just need write class for tracker and parser will be work

Thats a great idea. We could refactor the PT torrent search feature so that it utilizes Jacket to fetch more results and then use the Tracker Classes in Spider e.g. (Eztv, Rarabg etc.) to parse the results in a PT understandable way.

Also the way this should be implemented is like an interface so that anyone can easily write and add more Tracker classes


Currently as i understand each client in Spiders performs both the API call to the tracker and the parsing to the PT format. However what would be ideal is to let Jacket perform the search in all the trackers, an then use Spider clients only for the mapping to PT format

**Comment by ivan1986** [comment]
yes, greate we may use jacket on server for search from PT
Tracker classes now implement interface.
Now Spiders run in queue and go to pages of forums, get all new torrents and put it to database
we can not ask jacket get new topics form this day as i know
now cron worker run every day and grab new forum topics from trackers, how it implement in jacket?

**Comment by SergioBueno27** [comment]
Hi Ivan,
this looks like exactly what popcorn app needs keep the good work :+1:

**Comment by ivan1986** [comment]
@SergioBueno27 use https://popcorn-time.ga/build-ru/dev/ for now, i wait when @kiriles90 merge this, and it feature will be in next release

**Comment by SergioBueno27** [comment]
@ivan1986  for sure I will i didn't notice that it was available there

**Pull request merged**
