### PR TITLE
Little UX improvment on quality selector in show detail page

### PR DESCRIPTION
**Pull request by Persei08**
https://github.com/popcorn-official/popcorn-desktop/issues/306

This issue is actually closed but at begin you was a bit interested

Add a rounds corners background around the selected/choosed quality.
Should improve a bit UX.

PS: my editor removed some whitespaces too

### CODE REVIEW

**Comment by team-pct** [comment]
Can you open this PR on https://github.com/butterproject/butter-desktop 

Thank you for your contribution !

**Comment by Persei08** [comment]
https://github.com/butterproject/butter-desktop/pull/524

Is this ok with all this commits inside, or I should do it another way?

**Comment by team-pct** [comment]
Hmm you should fork directly Butter and send PR there and we will cherry-pick from there

**Comment by VitorVRS** [comment]
You could add butter as an another remote on your repo, create an branch on top o butter/master and push.

> git remote add butter git://github.com/...

And you can create an PR to butter.

**Comment by Persei08** [comment]
Thx, I submitted a new PR: https://github.com/butterproject/butter-desktop/pull/529

**Pull request closed without merging**
