### PR TITLE
Fix dht

### PR DESCRIPTION
**Pull request by ivan1986**

### CODE REVIEW

**Comment by ivan1986** [comment]
https://github.com/popcorn-time-ru/popcorn-desktop/actions/runs/11690810976
it was issue with new version of app pack

**Comment by ivan1986** [comment]
More than one architectures were found of the AppDir source directory "Popcorn-Time-0.5.1+51.g43f9849f.AppDir"

new lib contains prebuild and many arch - need force set arch

**Comment by ivan1986** [comment]
@kiriles90 look pls

**Review by rafaell-lycan — APPROVED** [review]
Just tested locally and works!

**Pull request merged**
