### PR TITLE
Fixed jshint

### PR DESCRIPTION
**Pull request by dvarrazzo**
Fix build failures in gitlab CI and on commit.

### CODE REVIEW

**Comment by tspanu** [comment]
Will this fix this issue? https://github.com/popcorn-official/popcorn-desktop/issues/949

**Comment by ettoreboy** [comment]
I applied the same changes in my branch before seeing this, is this going to be merged in development?

**Comment by ettoreboy** [comment]
Hello, I created the same as this is required to move forward with other PRs. https://github.com/popcorn-official/popcorn-desktop/pull/1060

**Comment by Persei08** [comment]
Well, I close this because similar PR #1060 was merged and we also no longer need ffmpeg prebuilt

Thanks anyway

**Pull request closed without merging**
