### PR TITLE
WIP support for Apple Silicon

### PR DESCRIPTION
**Pull request by ghost**
Depends on https://github.com/nwjs-community/nw-builder/pull/547

### CODE REVIEW

**Comment by kiriles90** [comment]
Doesn't this also depend on NW.js? (for which there is already an open issue but its not so straightforward to update without breaking various stuff). What is this PR's point? Why not just update to the master branch when your PR there is merged? Also.. why were the linux instructions on how to get dev builds removed? (yes it leads to a dead domain right now but they should be updated when there is a new one not removed, unless we are removing dev builds and especially when you left the Windows instructions intact)

Anyway the main issue is that both NW.js/nw-builder should be updated at the same time to have a point of doing so closing this but do join the discussion at https://github.com/popcorn-official/popcorn-desktop/issues/2062, any input would be valuable.

**Comment by berard** [comment]
@kiriles90 if you had looked at the linked PR on nw-builder you'd see that it uses a mac-arm64 build of nw.js

**Comment by kiriles90** [comment]
@berard I did see it but I dont understand what your point is with this? Yes ofc is uses a mac-arm64 build how else would it work natively on apple silicon?

**Comment by ghost** [comment]
FYI thanks to a fix in the ARM build on nwjs, and with my [PR](https://github.com/nwjs-community/nw-builder/pull/547) on nw-builder, popcorn-desktop now successfully compiles and runs on M1.

**Comment by kiriles90** [comment]
@berard nice! any news on if this is getting merged so we don't have to switch to forks back and forth?

**Pull request closed without merging**
