### PR TITLE
Concat, minify and auto inject javascript sources into index.html

### PR DESCRIPTION
**Pull request by pcenta**
Workflow for concatenating and minifying javascript source files in correct order into one file and auto injecting minified/non-minified sources depending on build environment into index.html.

https://github.com/popcorn-official/popcorn-desktop/pull/1421

### CODE REVIEW

**Review by rafaell-lycan — APPROVED** [review]

**Comment by Persei08** [comment]
What are the impacts on debugging ?

Also, could not those tasks be done just on `gulp dist` ? maybe even optional with an extra parameter ?.. like something like `gulp dist --platforms=win64 --compress` ?

So it will give us more choices, and we will be able to generate both compressed and not and compare them.

**Comment by pcenta** [comment]
> What are the impacts on debugging ?
> 
> Also, could not those tasks be done just on `gulp dist` ? maybe even optional with an extra parameter ?.. like something like `gulp dist --platforms=win64 --compress` ?
> 
> So it will give us more choices, and we will be able to generate both compressed and not and compare them.

Debugging is fine for me. Downside is that there's only one source file for all the code but it's separated. Also on development mode no variable names etc. are changed.

Currently it keeps non minified and minified version when making installation package. Switching it is as simple as altering file name in index.html.
I think that we should avoid trying not to concat sources because if we keep concat for development mode we make sure that there isn't any code that would break production build.

**Comment by Persei08** [comment]
ok, thx for explanations.

I will test it soon.

**Comment by rafaell-lycan** [comment]
@Persei08 there are some conflicts to be solved.

Cheers

**Comment by pcenta** [comment]
I fixed those conflicts. Can anyone else test this (development and production build).
So the logic is that if you build it locally it will use non minified (but concatenated) javascript file. For production build it should grab minified version.

**Comment by Yoric** [comment]
Out of curiosity, what's the point of concatenating/minifying/inecting on a desktop app?

The cost of local initial I/O is negligible, so I'm not sure what is gained, and I feel there there may be a net loss in debuggability.

**Comment by kiriles90** [comment]
Closing this for now but we can reopen if someone has a valid argument that this will make any, even if slight, measurable difference in performance and will not just be a drawback for debugging.

**Pull request closed without merging**
