### PR TITLE
Dependabot updates

### PR DESCRIPTION
**Pull request by pcenta**
Merge security related commits created by dependabot.

### CODE REVIEW

**Comment by kiriles90** [comment]
@pcenta any idea why #1562 is different?

**Comment by pcenta** [comment]
> @pcenta any idea why #1562 is different?

Good question but I am not sure. Could be that #1562 is dated to 20th of July and one in this PR is newer.

**Comment by kiriles90** [comment]
You are probably right. Closing it too since if we are going to merge one of them it should be the newer one. In the slim chance that is needed, we know where to find it.

**Comment by Persei08** [comment]
@team-pct told me to ignore those @dependabot PRs... to not merge them.

and If i update the packages.json with lodash ^4.17.19 and yarn install, it just update yarn.lock with lodash 4.17.20. It don't update all those other modules :/

**Comment by pcenta** [comment]
> @team-pct told me to ignore those @dependabot PRs... to not merge them.
> 
> and If i update the packages.json with lodash ^4.17.19 and yarn install, it just update yarn.lock with lodash 4.17.20. It don't update all those other modules :/

Ok, sure. I don't really have that much experience with node.js and yarn so I just gathered commits in one PR. Then this PR can be closed?

**Comment by Persei08** [comment]
@pcenta yeah no, I'm not too familiar with yarn or node too. I've mixed feeling about updating modules. I want to update them, but also fear it generate bugs we don't notice early enough...

I will merge it, after all this yarn.lock deserve to be updated

**Comment by kiriles90** [comment]
Had to be done at some point. Though.. now maybe we need build 442? Get more eyes on it see if any issue surfaces or all is good? (and before anything else important gets merged)

**Pull request merged**
