### PR TITLE
Fix options to disable the Indie/anime tab

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
I just added 20 lines, I don't know what it says that I took 727 and added 747.

**Comment by VitorVRS** [comment]
Did you change file enconding or something?

**Comment by ghost** [comment]
@VitorVRS No it's just a reupload of an @Persei08 issue

**Comment by Persei08** [comment]
I guess he want to know if it said 747 lines were changed because you used another encoding.

What text-editor have you used to edit the file?

**Comment by VitorVRS** [comment]
Try to diff via CLI using raw diff to see if it helps

**Comment by ghost** [comment]
@Persei08 Atom

**Comment by Persei08** [comment]
@Nallat the reason the diff consider all lines changed is because your line endings is windows format instead of unix. 
You can handle that with git: https://help.github.com/articles/dealing-with-line-endings

**Pull request closed without merging**
